// Generated by gencpp from file ros_opcua_srvs/Connect.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_CONNECT_H
#define ROS_OPCUA_SRVS_MESSAGE_CONNECT_H

#include <ros/service_traits.h>


#include <ros_opcua_srvs/ConnectRequest.h>
#include <ros_opcua_srvs/ConnectResponse.h>


namespace ros_opcua_srvs
{

struct Connect
{

typedef ConnectRequest Request;
typedef ConnectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Connect
} // namespace ros_opcua_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opcua_srvs::Connect > {
  static const char* value()
  {
    return "7339b9b9dcb669a384869db171c460ad";
  }

  static const char* value(const ::ros_opcua_srvs::Connect&) { return value(); }
};

template<>
struct DataType< ::ros_opcua_srvs::Connect > {
  static const char* value()
  {
    return "ros_opcua_srvs/Connect";
  }

  static const char* value(const ::ros_opcua_srvs::Connect&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opcua_srvs::ConnectRequest> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Connect >
template<>
struct MD5Sum< ::ros_opcua_srvs::ConnectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Connect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ConnectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::ConnectRequest> should match
// service_traits::DataType< ::ros_opcua_srvs::Connect >
template<>
struct DataType< ::ros_opcua_srvs::ConnectRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Connect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ConnectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opcua_srvs::ConnectResponse> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Connect >
template<>
struct MD5Sum< ::ros_opcua_srvs::ConnectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Connect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ConnectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::ConnectResponse> should match
// service_traits::DataType< ::ros_opcua_srvs::Connect >
template<>
struct DataType< ::ros_opcua_srvs::ConnectResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Connect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ConnectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_CONNECT_H
