// Generated by gencpp from file ros_opcua_srvs/ConnectRequest.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_CONNECTREQUEST_H
#define ROS_OPCUA_SRVS_MESSAGE_CONNECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_opcua_srvs
{
template <class ContainerAllocator>
struct ConnectRequest_
{
  typedef ConnectRequest_<ContainerAllocator> Type;

  ConnectRequest_()
    : endpoint()  {
    }
  ConnectRequest_(const ContainerAllocator& _alloc)
    : endpoint(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _endpoint_type;
  _endpoint_type endpoint;





  typedef boost::shared_ptr< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConnectRequest_

typedef ::ros_opcua_srvs::ConnectRequest_<std::allocator<void> > ConnectRequest;

typedef boost::shared_ptr< ::ros_opcua_srvs::ConnectRequest > ConnectRequestPtr;
typedef boost::shared_ptr< ::ros_opcua_srvs::ConnectRequest const> ConnectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.endpoint == rhs.endpoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_opcua_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "271aa4be505330f3d0735576816a63bb";
  }

  static const char* value(const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x271aa4be505330f3ULL;
  static const uint64_t static_value2 = 0xd0735576816a63bbULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_srvs/ConnectRequest";
  }

  static const char* value(const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string endpoint\n"
;
  }

  static const char* value(const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.endpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConnectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opcua_srvs::ConnectRequest_<ContainerAllocator>& v)
  {
    s << indent << "endpoint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.endpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_CONNECTREQUEST_H
