// Generated by gencpp from file ros_opcua_srvs/Disconnect.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_DISCONNECT_H
#define ROS_OPCUA_SRVS_MESSAGE_DISCONNECT_H

#include <ros/service_traits.h>


#include <ros_opcua_srvs/DisconnectRequest.h>
#include <ros_opcua_srvs/DisconnectResponse.h>


namespace ros_opcua_srvs
{

struct Disconnect
{

typedef DisconnectRequest Request;
typedef DisconnectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Disconnect
} // namespace ros_opcua_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opcua_srvs::Disconnect > {
  static const char* value()
  {
    return "6fe914479ce03184a758c3f6990c928f";
  }

  static const char* value(const ::ros_opcua_srvs::Disconnect&) { return value(); }
};

template<>
struct DataType< ::ros_opcua_srvs::Disconnect > {
  static const char* value()
  {
    return "ros_opcua_srvs/Disconnect";
  }

  static const char* value(const ::ros_opcua_srvs::Disconnect&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opcua_srvs::DisconnectRequest> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Disconnect >
template<>
struct MD5Sum< ::ros_opcua_srvs::DisconnectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Disconnect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::DisconnectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::DisconnectRequest> should match
// service_traits::DataType< ::ros_opcua_srvs::Disconnect >
template<>
struct DataType< ::ros_opcua_srvs::DisconnectRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Disconnect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::DisconnectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opcua_srvs::DisconnectResponse> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Disconnect >
template<>
struct MD5Sum< ::ros_opcua_srvs::DisconnectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Disconnect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::DisconnectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::DisconnectResponse> should match
// service_traits::DataType< ::ros_opcua_srvs::Disconnect >
template<>
struct DataType< ::ros_opcua_srvs::DisconnectResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Disconnect >::value();
  }
  static const char* value(const ::ros_opcua_srvs::DisconnectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_DISCONNECT_H
