// Generated by gencpp from file ros_opcua_srvs/ListNodeRequest.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_LISTNODEREQUEST_H
#define ROS_OPCUA_SRVS_MESSAGE_LISTNODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_opcua_msgs/Address.h>

namespace ros_opcua_srvs
{
template <class ContainerAllocator>
struct ListNodeRequest_
{
  typedef ListNodeRequest_<ContainerAllocator> Type;

  ListNodeRequest_()
    : node()  {
    }
  ListNodeRequest_(const ContainerAllocator& _alloc)
    : node(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ros_opcua_msgs::Address_<ContainerAllocator>  _node_type;
  _node_type node;





  typedef boost::shared_ptr< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListNodeRequest_

typedef ::ros_opcua_srvs::ListNodeRequest_<std::allocator<void> > ListNodeRequest;

typedef boost::shared_ptr< ::ros_opcua_srvs::ListNodeRequest > ListNodeRequestPtr;
typedef boost::shared_ptr< ::ros_opcua_srvs::ListNodeRequest const> ListNodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_opcua_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8550fb7b375751dffeab1627285bf027";
  }

  static const char* value(const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8550fb7b375751dfULL;
  static const uint64_t static_value2 = 0xfeab1627285bf027ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_srvs/ListNodeRequest";
  }

  static const char* value(const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_msgs/Address node\n"
"\n"
"================================================================================\n"
"MSG: ros_opcua_msgs/Address\n"
"string nodeId\n"
"string qualifiedName\n"
;
  }

  static const char* value(const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListNodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opcua_srvs::ListNodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    s << std::endl;
    Printer< ::ros_opcua_msgs::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.node);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_LISTNODEREQUEST_H
