// Generated by gencpp from file ros_opcua_srvs/ListNode.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_LISTNODE_H
#define ROS_OPCUA_SRVS_MESSAGE_LISTNODE_H

#include <ros/service_traits.h>


#include <ros_opcua_srvs/ListNodeRequest.h>
#include <ros_opcua_srvs/ListNodeResponse.h>


namespace ros_opcua_srvs
{

struct ListNode
{

typedef ListNodeRequest Request;
typedef ListNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListNode
} // namespace ros_opcua_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opcua_srvs::ListNode > {
  static const char* value()
  {
    return "b2a7f7743df0b9b4b3bc49d484a1e868";
  }

  static const char* value(const ::ros_opcua_srvs::ListNode&) { return value(); }
};

template<>
struct DataType< ::ros_opcua_srvs::ListNode > {
  static const char* value()
  {
    return "ros_opcua_srvs/ListNode";
  }

  static const char* value(const ::ros_opcua_srvs::ListNode&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opcua_srvs::ListNodeRequest> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::ListNode >
template<>
struct MD5Sum< ::ros_opcua_srvs::ListNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::ListNode >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ListNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::ListNodeRequest> should match
// service_traits::DataType< ::ros_opcua_srvs::ListNode >
template<>
struct DataType< ::ros_opcua_srvs::ListNodeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::ListNode >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ListNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opcua_srvs::ListNodeResponse> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::ListNode >
template<>
struct MD5Sum< ::ros_opcua_srvs::ListNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::ListNode >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ListNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::ListNodeResponse> should match
// service_traits::DataType< ::ros_opcua_srvs::ListNode >
template<>
struct DataType< ::ros_opcua_srvs::ListNodeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::ListNode >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ListNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_LISTNODE_H
