// Generated by gencpp from file ros_opcua_srvs/Read.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_READ_H
#define ROS_OPCUA_SRVS_MESSAGE_READ_H

#include <ros/service_traits.h>


#include <ros_opcua_srvs/ReadRequest.h>
#include <ros_opcua_srvs/ReadResponse.h>


namespace ros_opcua_srvs
{

struct Read
{

typedef ReadRequest Request;
typedef ReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Read
} // namespace ros_opcua_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opcua_srvs::Read > {
  static const char* value()
  {
    return "3e13de5d032d585d8ddea12c7428cac1";
  }

  static const char* value(const ::ros_opcua_srvs::Read&) { return value(); }
};

template<>
struct DataType< ::ros_opcua_srvs::Read > {
  static const char* value()
  {
    return "ros_opcua_srvs/Read";
  }

  static const char* value(const ::ros_opcua_srvs::Read&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opcua_srvs::ReadRequest> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Read >
template<>
struct MD5Sum< ::ros_opcua_srvs::ReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Read >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::ReadRequest> should match
// service_traits::DataType< ::ros_opcua_srvs::Read >
template<>
struct DataType< ::ros_opcua_srvs::ReadRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Read >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opcua_srvs::ReadResponse> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Read >
template<>
struct MD5Sum< ::ros_opcua_srvs::ReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Read >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::ReadResponse> should match
// service_traits::DataType< ::ros_opcua_srvs::Read >
template<>
struct DataType< ::ros_opcua_srvs::ReadResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Read >::value();
  }
  static const char* value(const ::ros_opcua_srvs::ReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_READ_H
