// Generated by gencpp from file ros_opcua_srvs/Subscribe.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_SUBSCRIBE_H
#define ROS_OPCUA_SRVS_MESSAGE_SUBSCRIBE_H

#include <ros/service_traits.h>


#include <ros_opcua_srvs/SubscribeRequest.h>
#include <ros_opcua_srvs/SubscribeResponse.h>


namespace ros_opcua_srvs
{

struct Subscribe
{

typedef SubscribeRequest Request;
typedef SubscribeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Subscribe
} // namespace ros_opcua_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opcua_srvs::Subscribe > {
  static const char* value()
  {
    return "611f15914760b79ca1b609342b109c53";
  }

  static const char* value(const ::ros_opcua_srvs::Subscribe&) { return value(); }
};

template<>
struct DataType< ::ros_opcua_srvs::Subscribe > {
  static const char* value()
  {
    return "ros_opcua_srvs/Subscribe";
  }

  static const char* value(const ::ros_opcua_srvs::Subscribe&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opcua_srvs::SubscribeRequest> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Subscribe >
template<>
struct MD5Sum< ::ros_opcua_srvs::SubscribeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Subscribe >::value();
  }
  static const char* value(const ::ros_opcua_srvs::SubscribeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::SubscribeRequest> should match
// service_traits::DataType< ::ros_opcua_srvs::Subscribe >
template<>
struct DataType< ::ros_opcua_srvs::SubscribeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Subscribe >::value();
  }
  static const char* value(const ::ros_opcua_srvs::SubscribeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opcua_srvs::SubscribeResponse> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Subscribe >
template<>
struct MD5Sum< ::ros_opcua_srvs::SubscribeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Subscribe >::value();
  }
  static const char* value(const ::ros_opcua_srvs::SubscribeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::SubscribeResponse> should match
// service_traits::DataType< ::ros_opcua_srvs::Subscribe >
template<>
struct DataType< ::ros_opcua_srvs::SubscribeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Subscribe >::value();
  }
  static const char* value(const ::ros_opcua_srvs::SubscribeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_SUBSCRIBE_H
