// Generated by gencpp from file ros_opcua_srvs/SubscribeRequest.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_SUBSCRIBEREQUEST_H
#define ROS_OPCUA_SRVS_MESSAGE_SUBSCRIBEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_opcua_msgs/Address.h>

namespace ros_opcua_srvs
{
template <class ContainerAllocator>
struct SubscribeRequest_
{
  typedef SubscribeRequest_<ContainerAllocator> Type;

  SubscribeRequest_()
    : node()
    , callback_topic()  {
    }
  SubscribeRequest_(const ContainerAllocator& _alloc)
    : node(_alloc)
    , callback_topic(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ros_opcua_msgs::Address_<ContainerAllocator>  _node_type;
  _node_type node;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _callback_topic_type;
  _callback_topic_type callback_topic;





  typedef boost::shared_ptr< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SubscribeRequest_

typedef ::ros_opcua_srvs::SubscribeRequest_<std::allocator<void> > SubscribeRequest;

typedef boost::shared_ptr< ::ros_opcua_srvs::SubscribeRequest > SubscribeRequestPtr;
typedef boost::shared_ptr< ::ros_opcua_srvs::SubscribeRequest const> SubscribeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node &&
    lhs.callback_topic == rhs.callback_topic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_opcua_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76af75c8aa2949c653fb7fd726b3a1bc";
  }

  static const char* value(const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76af75c8aa2949c6ULL;
  static const uint64_t static_value2 = 0x53fb7fd726b3a1bcULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_srvs/SubscribeRequest";
  }

  static const char* value(const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_msgs/Address node\n"
"string callback_topic\n"
"\n"
"================================================================================\n"
"MSG: ros_opcua_msgs/Address\n"
"string nodeId\n"
"string qualifiedName\n"
;
  }

  static const char* value(const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.callback_topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubscribeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opcua_srvs::SubscribeRequest_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    s << std::endl;
    Printer< ::ros_opcua_msgs::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.node);
    s << indent << "callback_topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.callback_topic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_SUBSCRIBEREQUEST_H
