// Generated by gencpp from file ros_opcua_srvs/Write.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_WRITE_H
#define ROS_OPCUA_SRVS_MESSAGE_WRITE_H

#include <ros/service_traits.h>


#include <ros_opcua_srvs/WriteRequest.h>
#include <ros_opcua_srvs/WriteResponse.h>


namespace ros_opcua_srvs
{

struct Write
{

typedef WriteRequest Request;
typedef WriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Write
} // namespace ros_opcua_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opcua_srvs::Write > {
  static const char* value()
  {
    return "6b8afc0b78657683449df0e603595707";
  }

  static const char* value(const ::ros_opcua_srvs::Write&) { return value(); }
};

template<>
struct DataType< ::ros_opcua_srvs::Write > {
  static const char* value()
  {
    return "ros_opcua_srvs/Write";
  }

  static const char* value(const ::ros_opcua_srvs::Write&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opcua_srvs::WriteRequest> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Write >
template<>
struct MD5Sum< ::ros_opcua_srvs::WriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Write >::value();
  }
  static const char* value(const ::ros_opcua_srvs::WriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::WriteRequest> should match
// service_traits::DataType< ::ros_opcua_srvs::Write >
template<>
struct DataType< ::ros_opcua_srvs::WriteRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Write >::value();
  }
  static const char* value(const ::ros_opcua_srvs::WriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opcua_srvs::WriteResponse> should match
// service_traits::MD5Sum< ::ros_opcua_srvs::Write >
template<>
struct MD5Sum< ::ros_opcua_srvs::WriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opcua_srvs::Write >::value();
  }
  static const char* value(const ::ros_opcua_srvs::WriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opcua_srvs::WriteResponse> should match
// service_traits::DataType< ::ros_opcua_srvs::Write >
template<>
struct DataType< ::ros_opcua_srvs::WriteResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opcua_srvs::Write >::value();
  }
  static const char* value(const ::ros_opcua_srvs::WriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_WRITE_H
