// Generated by gencpp from file ros_opcua_srvs/WriteResponse.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_WRITERESPONSE_H
#define ROS_OPCUA_SRVS_MESSAGE_WRITERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_opcua_srvs
{
template <class ContainerAllocator>
struct WriteResponse_
{
  typedef WriteResponse_<ContainerAllocator> Type;

  WriteResponse_()
    : success(false)
    , error_message()  {
    }
  WriteResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WriteResponse_

typedef ::ros_opcua_srvs::WriteResponse_<std::allocator<void> > WriteResponse;

typedef boost::shared_ptr< ::ros_opcua_srvs::WriteResponse > WriteResponsePtr;
typedef boost::shared_ptr< ::ros_opcua_srvs::WriteResponse const> WriteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_message == rhs.error_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_opcua_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fe914479ce03184a758c3f6990c928f";
  }

  static const char* value(const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fe914479ce03184ULL;
  static const uint64_t static_value2 = 0xa758c3f6990c928fULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_srvs/WriteResponse";
  }

  static const char* value(const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string error_message\n"
;
  }

  static const char* value(const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opcua_srvs::WriteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opcua_srvs::WriteResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_WRITERESPONSE_H
