// Generated by gencpp from file ros_opcua_srvs/WriteRequest.msg
// DO NOT EDIT!


#ifndef ROS_OPCUA_SRVS_MESSAGE_WRITEREQUEST_H
#define ROS_OPCUA_SRVS_MESSAGE_WRITEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_opcua_msgs/Address.h>
#include <ros_opcua_msgs/TypeValue.h>

namespace ros_opcua_srvs
{
template <class ContainerAllocator>
struct WriteRequest_
{
  typedef WriteRequest_<ContainerAllocator> Type;

  WriteRequest_()
    : node()
    , data()  {
    }
  WriteRequest_(const ContainerAllocator& _alloc)
    : node(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ros_opcua_msgs::Address_<ContainerAllocator>  _node_type;
  _node_type node;

   typedef  ::ros_opcua_msgs::TypeValue_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteRequest_

typedef ::ros_opcua_srvs::WriteRequest_<std::allocator<void> > WriteRequest;

typedef boost::shared_ptr< ::ros_opcua_srvs::WriteRequest > WriteRequestPtr;
typedef boost::shared_ptr< ::ros_opcua_srvs::WriteRequest const> WriteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator1> & lhs, const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_opcua_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72d070c751907fd5ca2b477a8e081323";
  }

  static const char* value(const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72d070c751907fd5ULL;
  static const uint64_t static_value2 = 0xca2b477a8e081323ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_srvs/WriteRequest";
  }

  static const char* value(const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opcua_msgs/Address node\n"
"ros_opcua_msgs/TypeValue data\n"
"\n"
"================================================================================\n"
"MSG: ros_opcua_msgs/Address\n"
"string nodeId\n"
"string qualifiedName\n"
"================================================================================\n"
"MSG: ros_opcua_msgs/TypeValue\n"
"# This represents OPC-UA type-value pair\n"
"string type\n"
"bool bool_d\n"
"int8 int8_d\n"
"uint8 uint8_d\n"
"int16 int16_d\n"
"uint16 uint16_d\n"
"int32 int32_d\n"
"uint32 uint32_d\n"
"int64 int64_d\n"
"uint64 uint64_d\n"
"float32 float_d\n"
"float64 double_d\n"
"string string_d\n"
;
  }

  static const char* value(const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opcua_srvs::WriteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opcua_srvs::WriteRequest_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    s << std::endl;
    Printer< ::ros_opcua_msgs::Address_<ContainerAllocator> >::stream(s, indent + "  ", v.node);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::ros_opcua_msgs::TypeValue_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPCUA_SRVS_MESSAGE_WRITEREQUEST_H
